"""fix user models, enums

Revision ID: 32b4ab00dcc5
Revises: 4bd56c12e735
Create Date: 2025-06-16 08:34:39.944834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b4ab00dcc5'
down_revision = '4bd56c12e735'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
