"""new migration

Revision ID: 8863a66d4075
Revises: bac86bbab8f5
Create Date: 2025-06-15 12:51:39.647364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8863a66d4075'
down_revision = 'bac86bbab8f5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
